version: 2

jobs:
  build:
    docker:
      - image: node:9
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
